OPENAI_API_KEY =  #API Key obtida na conta da OPENAI 

ASSISTENTE =    #ID do Assistente definido na conta da OPENAI

[auth]  #INFORMACOES DO LOGIN DO GOOGLE - VEJA MAIS NA DOCUMENTACAO DE ST.LOGIN DO STREAMLIT
redirect_uri = "http://localhost:8501/oauth2callback"
cookie_secret =  
client_id = 
client_secret =  
server_metadata_url = "https://accounts.google.com/.well-known/openid-configuration"

[firebase]    #INFORMACACOES SOBRE A CONECAO COM O GOOGLE FIREBASE
type =  
project_id =  
private_key_id =  
private_key =  
client_email =  
client_id =  
auth_uri =  
token_uri =  
auth_provider_x509_cert_url =  
client_x509_cert_url =  
universe_domain =  

  
